# ============================================================
# CONFIGURE FOR EACH DATASET
# ============================================================
CONFIGS = {
    # Bhutan Telecom
    'bt_postpaid_voice': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/bt_postpaid/voice',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cdr_postpaid_voice',
        'location': 's3://data-lake-bucket/bhutan_telecom/cdr/postpaid/voice/',
    },
    'bt_postpaid_sms': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/bt_postpaid/sms',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cdr_postpaid_sms',
        'location': 's3://data-lake-bucket/bhutan_telecom/cdr/postpaid/sms/',
    },
    'bt_postpaid_data': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/bt_postpaid/data',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cdr_postpaid_data',
        'location': 's3://data-lake-bucket/bhutan_telecom/cdr/postpaid/data/',
    },
    'bt_prepaid_data': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/bt_prepaid/data',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cdr_prepaid_data',
        'location': 's3://data-lake-bucket/bhutan_telecom/cdr/prepaid/data/',
    },
    'customer_complaints': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/customer_complaints',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'customer_complaints',
        'location': 's3://data-lake-bucket/bhutan_telecom/customer_complaints/',
    },
    'cell_tower_details': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/cell_tower',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_details',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/cell_tower_details',
    },
    'cell_tower_data_traffic_summary': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/data_traffic_summary',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_data_traffic_summary',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/data_traffic_summary',
    },
    'cell_tower_kpi': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/kpi',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_kpi',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/kpi',
    },
    'cell_tower_kpi_report': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/kpi_report',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_kpi_report',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/kpi_report',
    },
    'cell_tower_data_traffic': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/voice_&_data_traffic/data_traffic',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_data_traffic',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/voice_and_data_traffic/data_traffic',
    },
    'cell_tower_voice_traffic': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/cell_tower/voice_&_data_traffic/voice_traffic',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'cell_tower_voice_traffic',
        'location': 's3://data-lake-bucket/bhutan_telecom/cell_tower/voice_and_data_traffic/voice_traffic',
    },
    'monthly_revenue_data': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/monthly_revenue/revenue_data',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'monthly_revenue_data',
        'location': 's3://data-lake-bucket/bhutan_telecom/monthly_revenue/revenue_data/',
    },
    'monthly_revenue_sms': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/monthly_revenue/revenue_sms',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'monthly_revenue_sms',
        'location': 's3://data-lake-bucket/bhutan_telecom/monthly_revenue/revenue_sms/',
    },
    'monthly_revenue_voice': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/monthly_revenue/revenue_voice',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'monthly_revenue_voice',
        'location': 's3://data-lake-bucket/bhutan_telecom/monthly_revenue/revenue_voice/',
    },
    'postpaid_tariff_booster': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/postpaid_tariff/booster_plan',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'postpaid_tariff_booster',
        'location': 's3://data-lake-bucket/bhutan_telecom/postpaid_tariff/booster_plan/',
    },
    'postpaid_tariff_monthly': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/postpaid_tariff/monthly_plan',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'postpaid_tariff_monthly',
        'location': 's3://data-lake-bucket/bhutan_telecom/postpaid_tariff/monthly_plan/',
    },
    'postpaid_tariff_sms': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/postpaid_tariff/sms_tariff',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'postpaid_tariff_sms',
        'location': 's3://data-lake-bucket/bhutan_telecom/postpaid_tariff/sms_tariff/',
    },
    'postpaid_tariff_voice': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/postpaid_tariff/voice_tariff',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'postpaid_tariff_voice',
        'location': 's3://data-lake-bucket/bhutan_telecom/postpaid_tariff/voice_tariff/',
    },
    'prepaid_tariff_air_fibre': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/prepaid_tariff/air_fibre_plan',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'prepaid_tariff_air_fibre',
        'location': 's3://data-lake-bucket/bhutan_telecom/prepaid_tariff/air_fibre_plan/',
    },
    'prepaid_tariff_data_plan': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/prepaid_tariff/data_plan',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'prepaid_tariff_data_plan',
        'location': 's3://data-lake-bucket/bhutan_telecom/prepaid_tariff/data_plan/',
    },
    'prepaid_tariff_voice_sms': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/bhutan_telecom/prepaid_tariff/voice_and_sms_tariff',
        'catalog': 'iceberg',
        'schema': 'bhutan_telecom',
        'table': 'prepaid_tariff_voice_sms',
        'location': 's3://data-lake-bucket/bhutan_telecom/prepaid_tariff/voice_and_sms_tariff/',
    },

    #================================================================================================================
    # Drukair
    'passenger_traffic': {
        'local_base': '/Users/tashigyeltshen/Downloads/temp_data/passenger_parquet',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'passenger_traffic',
    },
    'balance_sheet': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/financial_report/balance_sheet',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'balance_sheet',
        'location': 's3://data-lake-bucket/drukair/financial_report/balance_sheet/',
    },
    'cash_flow': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/financial_report/cash_flow',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'cash_flow',
        'location': 's3://data-lake-bucket/drukair/financial_report/cash_flow/',
    },
    'profit_loss': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/financial_report/profit_and_loss',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'profit_loss',
        'location': 's3://data-lake-bucket/drukair/financial_report/profit_and_loss/',
    },
    'master_data_2018': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2018',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2018',
        'location': 's3://data-lake-bucket/drukair/master_data/2018/',
    },
    'master_data_2019': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2019',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2019',
        'location': 's3://data-lake-bucket/drukair/master_data/2019/',
    },
    'master_data_2020': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2020',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2020',
        'location': 's3://data-lake-bucket/drukair/master_data/2020/',
    },
    'master_data_2021': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2021',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2021',
        'location': 's3://data-lake-bucket/drukair/master_data/2021/',
    },
    'master_data_2022': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2022',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2022',
        'location': 's3://data-lake-bucket/drukair/master_data/2022/',
    },
    'master_data_2023': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2023',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2023',
        'location': 's3://data-lake-bucket/drukair/master_data/2023/',
    },
    'master_data_2024': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2024',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2024',
        'location': 's3://data-lake-bucket/drukair/master_data/2024/',
    },
    'master_data_2025': {
        'local_base': '/Users/tashigyeltshen/Downloads/DHI_IA/parquet_files/drukair/master_data/2025',
        'catalog': 'iceberg',
        'schema': 'drukair',
        'table': 'master_data_2025',
        'location': 's3://data-lake-bucket/drukair/master_data/2025/',
    },
}r_data_2025',
        'location': 's3://data-lake-bucket/drukair/master_data/2025/',
    },
}